baseURL: "https://yuanprogram.github.io/"
title: "Yuan's Blog"
theme: "PaperMod"  # 改为单引号

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts"]  # 简化

minify:
  disableXML: true

pagination:
  disableAliases: false
  pagerSize: 5

languages:
  zh-cn:
    languageName: "简体中文"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: "首页"
          url: "/"
          weight: 10
        - name: "文章"
          url: "/posts/"
          weight: 20
        - name: "分类"
          url: "/categories/"
          weight: 30
        - name: "标签"
          url: "/tags/"
          weight: 40
        - name: "关于"
          url: "/about/"
          weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "分享技术和生活的博客"
  author: "Yuan"
  
  defaultTheme: auto
  ShowShareButtons: true
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: true
    title: "Yuan"
    imageUrl: "/images/avatar.jpg"  # 替换为你的头像
    subtitle: "开发者 | 技术爱好者"
    buttons:
      - name: "文章"
        url: "/posts"
      - name: "分类"
        url: "/categories"

  homeInfoParams:
    Title: "Yuan's Blog"
    Content: >
      你好！我是 Yuan，一名开发者和技术爱好者。
      这里记录我的技术探索、项目经验和思考。欢迎交流！

  socialIcons:
    - name: github
      title: GitHub
      url: "https://github.com/yuanprogram"
    - name: email
      title: Email
      url: "2408170818@qq.com"  # 替换为你的邮箱

  editPost:
    URL: "https://github.com/yuanprogram/yuanprogram.github.io/tree/main/content"  # 指向你的仓库
    Text: "建议修改"
    appendFilePath: true

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false